name: android
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
     - master
     - 'feature/**'
    paths:
      - 'source/**'
      - 'express/**'
      - 'test/**'
      - 'project/android/**'
      - '.github/workflows/android.yml'
  pull_request:
    branches: [master]
    paths:
      - 'source/**'
      - 'express/**'
      - 'test/**'
      - 'project/android/**'
      - '.github/workflows/android.yml'

concurrency:
  group: android-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read

jobs:
  android_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build_android_64
        run: |
            cd project/android
            mkdir build_64
            cd build_64
            ../build_64.sh

      - name: Archive SO Files
        run: |
          rm -rf artifacts
          mkdir -p artifacts
          find . -name "*.so" -exec cp --parents {} artifacts \;  # 收集所有.so文件
          tar -czvf so-files.tar.gz -C artifacts .  # 打包成压缩文件

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-so-files
          path: so-files.tar.gz  # 上传压缩包
          retention-days: 7      # 保留时间（按需调整）
